pipeline {
  agent any
	 options {
        timestamps()
    }
  tools {
        maven 'maven-3'
        jdk 'JDK'
    }
  environment {
        DOCKERHUB_USER = "nareshbashipangu"
        IMAGE_NAME = "docker-demo"
        BUILD_TAG = "${BUILD_NUMBER}"
        IMAGE_WITH_BUILD = "${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_TAG}"
        IMAGE_LATEST = "${DOCKERHUB_USER}/${IMAGE_NAME}:latest"
		NAMESPACE = "local"
	    KUBECONFIG = "C:\\Users\\Hp\\.kube\\config"
    }
  stages {

	stage('Checkout') {
         steps {
          echo "Code checkout from github"
          git branch: 'main',
            url: 'https://github.com/nareshdevops2025/Docker.git'
      }
    }

     stage('Testing') {
            steps {
        dir('application') {
             echo "maven test"
                    bat 'mvn test'

                }
            }
        }

	stage('Package Build') {
            steps {
                dir('application') {
                  echo "Packaging java application"
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

	stage('Docker Build') {
         steps {
             dir('application') {
               echo "Building Docker image"
               bat "docker build -t %IMAGE_WITH_BUILD% ."
                     }
        }
      }

	stage('Tag Image as Latest') {
            steps {
			    echo "Tag docker image"     
                bat "docker tag %IMAGE_WITH_BUILD% %IMAGE_LATEST%"
            }
        }

    stage('Docker Build') {
    steps {
        dir('application') {
            echo "Building Docker image"
                bat "docker build -t %IMAGE_WITH_BUILD% ."
                     }
        }
      }

      stage('Tag Image as Latest') {
            steps {
                bat "docker tag %IMAGE_WITH_BUILD% %IMAGE_LATEST%"
            }
        }

       	stage('DockerHub Login') {
            steps {
				echo "Login into dockerhub"
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    bat "docker login -u %DOCKER_USER% -p %DOCKER_PASS%"
                }
            }
        }

	  stage('Docker Build') {
         steps {
             dir('application') {
               echo "Building Docker image"
               bat "docker build -t %IMAGE_WITH_BUILD% ."
			   echo "Push image into dockerhub"
               bat  'docker push %IMAGE_WITH_BUILD%'
                     }
        }
      }
	
        stage('Verify kubectl') {
            steps {
                bat 'kubectl version --client'
            }
        }

        stage('Verify Kubernetes Context') {
            steps {
                bat "docker images | findstr %IMAGE_NAME%"
            }
        }
    }

    post {
        success {
            echo "✅ Docker image tagged and pushed successfully!"
        }
        failure {
            echo "❌ Docker tagging or push failed"
        }
    }
  
	  
	  }
